### ISSUE TITLE
[docs] integration test example

### ISSUE THREAD

**Issue by tariqha-dev** [awslabs/solution-spark-on-aws#483]
It will really help to add more detail on the integration test procedure at
https://github.com/awslabs/solution-spark-on-aws/blob/main/solutions/swb-reference/README.md#integration-tests 

the instructions on editing the <stage>.yaml file is not clear. Where do I find the value for each fields? 
A screenshot of an example will really help

**Comment by FernandoAranda** [comment]
Hi @tariqha-dev thank you for bringing this to our attention,
We are working on adding more information to the integration test documentation, We'll keep this ticket updated with any news related to the documentation change.

Thanks 
Fernando

**Comment by SanketD92** [comment]
Hello @tariqha-dev, we have an [example](https://github.com/awslabs/solution-spark-on-aws/blob/main/solutions/swb-reference/integration-tests/config/example.yaml) file (commented) added to the repository as a reference.

A quick note about the config variables is as follows:
apiBaseUrl: This is the `apiUrlOutput` that becomes available after running the `cdk-deploy` command. Value found on console running the deploy command.

Resource creation and extracting values for the following can be found [here](https://github.com/awslabs/solution-spark-on-aws/blob/main/solutions/swb-reference/SETUP_v2p1.md)
envTypeId: The ID assigned to the SC environment type you've imported for the test. Value found
envTypeConfigId: The ID assigned to the SC environment type config linked to the envTypeId above
projectId: The ID of the project linked to the hosting account via index
envType: Name given to the envType (default is `sagemakerNotebook`)

alreadyTerminateEnvId: ID of a terminated environment

Details of the Cognito User Pool created in your main account by SWB:
`awsRegion`, `userPoolId`, `clientId` (app client ID)

rootUsername: email ID to use for login
rootPasswordParamStorePath: path of the SSM param where password for this user is stored

**Comment by FernandoAranda** [comment]
Hi @tariqha-dev we also have updated the instructions for integration testing [here](https://github.com/awslabs/solution-spark-on-aws/blob/develop/solutions/swb-reference/README.md).
I hope it helps

-Fernando
